version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD:
    ports:
      - "3307:3306"
    volumes:
      - vitheka-db:/var/lib/mysql

volumes:
  vitheka-db:
