version: '3.8'

services:
  mariadb:
    image: mariadb:10.10
    container_name: my-mariadb
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: mariadbPW
      MARIADB_ROOT_PASSWORD: mariadbrootPW
    ports:
      - "3308:3306"
    volumes:
      - vitheka-db:/var/lib/mysql

volumes:
  vitheka-db:
