spring:
  application:
    name: 'Customer'
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: jdbc:mariadb://localhost:3308/customerdb?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD:mariadbrootPW}

aws:
  region: 'us-east-1'
  sns:
    topic:
      product:
        events:
          arn: 'product-events'